//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class attendance_emp
    {
        [Required(ErrorMessage = "Employee ID has to be filled")]
        [Range(1, 10000)]
        public int empId { get; set; }
        [Required(ErrorMessage = "Status has to be filled")]
        public string status { get; set; }
        [Required(ErrorMessage = "Date has to be filled")]
        public string date { get; set; }
    }
}
