//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int billId { get; set; }
        public string Type { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
    }
}
