//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer
    {
        public int PaymentID { get; set; }
        public string TrainerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string Month { get; set; }
    }
}
