//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventorymgtEntities : DbContext
    {
        public inventorymgtEntities()
            : base("name=inventorymgtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<daily> dailies { get; set; }
        public virtual DbSet<income> incomes { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orderdetail> orderdetails { get; set; }
        public virtual DbSet<storeproduct> storeproducts { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<attendance_emp> attendance_emp { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<inventory_pay> inventory_pay { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<diet_planing> diet_planing { get; set; }
    }
}
