//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_pay
    {
        public int paymentId { get; set; }
        public string Type { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PayementDate { get; set; }
        public string Month { get; set; }
    }
}
