//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class leave
    {
        [Required(ErrorMessage = "Employee ID has to be filled")]
        [Range(1, 10000)]
        public int empId { get; set; }
        [Required(ErrorMessage = "Reason has to be filled")]
        public string reason { get; set; }
        [Required(ErrorMessage = "From date has to be filled")]
        public string fromdate { get; set; }

        [Required(ErrorMessage = "To date has to be filled")]
        public string todate { get; set; }
        [Required(ErrorMessage = "No of days has to be filled")]
        public string noofdays { get; set; }
    }
}
