//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int orderID { get; set; }
        public int product_ID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<float> price { get; set; }
    
        public virtual order order { get; set; }
        public virtual storeproduct storeproduct { get; set; }
    }
}
