//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class salary
    {





        [Required(ErrorMessage = "Employee ID has to be filled")]
        [Range(1, 10000)]
        public Nullable<int> empId { get; set; }


        [Required(ErrorMessage = "Basic Salary has to be filled")]
        [Range(1, 100000000)]
        public Nullable<double> basic { get; set; }

        [Required(ErrorMessage = "O/T hours has to be filled")]
        [Range(1, 30)]

        public Nullable<double> othours { get; set; }

        [Required(ErrorMessage = "O/T rate has to be filled")]
        [Range(1, 1000)]
        public Nullable<double> otrate { get; set; }

        [Required(ErrorMessage = "Bonus has to be filled")]
        [Range(1, 1000)]
        public Nullable<double> bonus { get; set; }
        public Nullable<double> otpay { get; set; }
        public Nullable<double> deduction { get; set; }
        public Nullable<double> netsal { get; set; }
    }
}
