//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class storeproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public storeproduct()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int product_ID { get; set; }
        public int itemCode { get; set; }
        public int titleID { get; set; }
        [Required]
        public string product_name { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        [Range(0,1000)]
        public Nullable<int> quantity { get; set; }
        [Range(0,50000)]
        public Nullable<float> price { get; set; }
    
        public virtual inventory inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual title title { get; set; }
    }
}
